In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
import torch
import random

warnings.filterwarnings("ignore")
%matplotlib inline

In [2]:
SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
torch.cuda.manual_seed_all(SEED)

In [3]:
SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
torch.cuda.manual_seed_all(SEED)

In [4]:
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [5]:
DEVICE

device(type='cuda')

In [6]:
PATH = "/kaggle/input/combind-ai-human-indo/combined_ai_human_indonesia.csv"

In [7]:
df = pd.read_csv(PATH)

In [8]:
df.head()

                                             message  label
0  Perusahaan manufaktur milik keluarga , PT Buka...      0
1  Federasi Sepak Bola Internasional, FIFA resmi ...      0
2  Silicon Valley Bank (SVB) telah mengibarkan be...      0
3       lebih enak naik pesawat daripada naik sepeda      0
4  Seabria adalah genus kumbang tanduk panjang ya...      0

In [9]:
df.tail()

                                                  message  label
209219  Angkong adalah suatu kendaraan bertenaga manus...      0
209220  anak-anak yang mengikuti dari belakang bisa me...      0
209221  Yerida ( yerida, "keturunan") adalah sebuah is...      0
209222  Olenecamptus nigromaculatus adalah spesies kum...      0
209223  Tipula (Eumicrotipula) pediformis adalah spesi...      0

In [10]:
df.shape

(209224, 2)

In [11]:
import re

In [12]:
def text_preprocessing(text):
    text = text.replace('-', ' ')
    text = re.sub(r'[\r\xa0\t]', '', text)
    text = re.sub(r"http\S+|www\S+", '', text)
    text = re.sub(r'\b\w*\.com\w*\b', '', text)
    text = re.sub(r'\[.*?\]|\(.*?\}|\{.*?\}', '', text)
    text = re.sub(r'\b(\w+)/(\w+)\b', r'\1 atau \2', text)
    text = re.sub(r'@[A-Za-z0-9]+|#[A-Za-z0-9]+', '', text)
    text = re.sub(r'[^\w\s]', '', text)
    text = re.sub(r'\s+', ' ', text)
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    return text.lower().strip()

In [13]:
def convert_label(label):
    return "ai" if label == 1.0 else "human"

In [14]:
df["label"] = df["label"].apply(convert_label)
df["message"] = df["message"].astype(str).apply(text_preprocessing)

In [15]:
df.head()

                                             message  label
0  perusahaan manufaktur milik keluarga pt bukaka...  human
1  federasi sepak bola internasional fifa resmi m...  human
2  silicon valley bank svb telah mengibarkan bend...  human
3       lebih enak naik pesawat daripada naik sepeda  human
4  seabria adalah genus kumbang tanduk panjang ya...  human

In [16]:
df = df[(df["message"].str.len() > 20) & (df["message"].str.len() < 2000)]
df = df.sample(frac=1, random_state=SEED).reset_index(drop=True)

In [17]:
df["label"] = df["label"].map({"ai": 1, "human": 0})

In [18]:
df["label"].value_counts()

label
1    99040
0    82131
Name: count, dtype: int64

In [19]:
X = df["message"]
y = df["label"].values

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
X_train, X_val, y_train, y_val = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=SEED
)

In [22]:
def construct_tagged_document(X, y):
    return [
        TaggedDocument(words=simple_preprocess(doc), tags=[y[i]])
        for i, doc in enumerate(X)
    ]

In [23]:
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset
from torch.optim import Adam
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from gensim.models import Doc2Vec
from gensim.models.doc2vec import TaggedDocument
from gensim.utils import simple_preprocess

In [24]:
train_tagged = construct_tagged_document(X_train, y_train)
val_tagged = construct_tagged_document(X_val, y_val)
data_tagged = train_tagged + val_tagged

In [25]:
import multiprocessing

In [26]:
INPUT_DIM = 1000
EPOCHS = 20
MIN_COUNT = 0
cores = multiprocessing.cpu_count()

In [27]:
cores

4

In [28]:
import os

In [29]:
BASE_DIR = "/kaggle/working/saved_models"
os.makedirs(BASE_DIR, exist_ok=True)

In [30]:
file_path = os.path.join(BASE_DIR, "doc2vec.d2v")

In [31]:
from tqdm import tqdm

In [32]:
if os.path.isfile(file_path):
    d2v = Doc2Vec.load(file_path)
else:
    d2v = Doc2Vec(
        dm=1,
        vector_size=INPUT_DIM,
        min_count=MIN_COUNT,
        workers=cores
    )
    d2v.build_vocab(data_tagged)

    for _ in tqdm(range(EPOCHS), desc="Training Doc2Vec"):
        d2v.train(data_tagged, total_examples=d2v.corpus_count, epochs=1)

    d2v.save(file_path)

Training Doc2Vec:   5%|▌         | 1/20 [00:36<11:30, 36.35s/it]WARNING:gensim.models.word2vec:Effective 'alpha' higher than previous training cycles
Training Doc2Vec:  10%|█         | 2/20 [01:10<10:33, 35.22s/it]WARNING:gensim.models.word2vec:Effective 'alpha' higher than previous training cycles
Training Doc2Vec:  15%|█▌        | 3/20 [01:45<09:53, 34.88s/it]WARNING:gensim.models.word2vec:Effective 'alpha' higher than previous training cycles
Training Doc2Vec:  20%|██        | 4/20 [02:19<09:15, 34.70s/it]WARNING:gensim.models.word2vec:Effective 'alpha' higher than previous training cycles
Training Doc2Vec:  25%|██▌       | 5/20 [02:54<08:38, 34.59s/it]WARNING:gensim.models.word2vec:Effective 'alpha' higher than previous training cycles
Training Doc2Vec:  30%|███       | 6/20 [03:28<08:02, 34.49s/it]WARNING:gensim.models.word2vec:Effective 'alpha' higher than previous training cycles
Training Doc2Vec:  35%|███▌      | 7/20 [04:02<07:28, 34.53s/it]WARNING:gensim.models.word2vec:Effective 'alpha' higher than previous training cycles
Training Doc2Vec:  40%|████      | 8/20 [04:37<06:53, 34.47s/it]WARNING:gensim.models.word2vec:Effective 'alpha' higher than previous training cycles
Training Doc2Vec:  45%|████▌     | 9/20 [05:11<06:17, 34.33s/it]WARNING:gensim.models.word2vec:Effective 'alpha' higher than previous training cycles
Training Doc2Vec:  50%|█████     | 10/20 [05:45<05:43, 34.39s/it]WARNING:gensim.models.word2vec:Effective 'alpha' higher than previous training cycles
Training Doc2Vec:  55%|█████▌    | 11/20 [06:19<05:08, 34.26s/it]WARNING:gensim.models.word2vec:Effective 'alpha' higher than previous training cycles
Training Doc2Vec:  60%|██████    | 12/20 [06:53<04:32, 34.07s/it]WARNING:gensim.models.word2vec:Effective 'alpha' higher than previous training cycles
Training Doc2Vec:  65%|██████▌   | 13/20 [07:27<03:57, 33.97s/it]WARNING:gensim.models.word2vec:Effective 'alpha' higher than previous training cycles
Training Doc2Vec:  70%|███████   | 14/20 [08:00<03:23, 33.91s/it]WARNING:gensim.models.word2vec:Effective 'alpha' higher than previous training cycles
Training Doc2Vec:  75%|███████▌  | 15/20 [08:34<02:49, 33.81s/it]WARNING:gensim.models.word2vec:Effective 'alpha' higher than previous training cycles
Training Doc2Vec:  80%|████████  | 16/20 [09:08<02:14, 33.73s/it]WARNING:gensim.models.word2vec:Effective 'alpha' higher than previous training cycles
Training Doc2Vec:  85%|████████▌ | 17/20 [09:41<01:40, 33.63s/it]WARNING:gensim.models.word2vec:Effective 'alpha' higher than previous training cycles
Training Doc2Vec:  90%|█████████ | 18/20 [10:14<01:07, 33.52s/it]WARNING:gensim.models.word2vec:Effective 'alpha' higher than previous training cycles
Training Doc2Vec:  95%|█████████▌| 19/20 [10:48<00:33, 33.65s/it]WARNING:gensim.models.word2vec:Effective 'alpha' higher than previous training cycles
Training Doc2Vec: 100%|██████████| 20/20 [11:21<00:00, 34.10s/it]

In [33]:
def infer_vectors(model, tagged_docs):
    features, labels = [], []
    for doc in tqdm(tagged_docs, desc="Inferring vectors"):
        features.append(model.infer_vector(doc.words, epochs=20))
        labels.append(doc.tags[0])
    return np.array(features), np.array(labels)

In [34]:
X_train_vec, y_train_vec = infer_vectors(d2v, train_tagged)
X_val_vec, y_val_vec = infer_vectors(d2v, val_tagged)

Inferring vectors: 100%|██████████| 144936/144936 [14:26<00:00, 167.17it/s]
Inferring vectors: 100%|██████████| 36235/36235 [03:38<00:00, 165.92it/s]

In [35]:
X_train_vec = X_train_vec.reshape(-1, INPUT_DIM, 1)
X_val_vec = X_val_vec.reshape(-1, INPUT_DIM, 1)

In [36]:
train_dataset = TensorDataset(
    torch.tensor(X_train_vec, dtype=torch.float32),
    torch.tensor(y_train_vec, dtype=torch.float32)
)

val_dataset = TensorDataset(
    torch.tensor(X_val_vec, dtype=torch.float32),
    torch.tensor(y_val_vec, dtype=torch.float32)
)

In [37]:
train_loader = DataLoader(train_dataset, batch_size=15, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=15, shuffle=False)`

SyntaxError: invalid syntax (180961281.py, line 2)

### LSTM

In [ ]:
import os

OUTPUT_DIR = "/kaggle/working/output"
MODEL_DIR = "/kaggle/working/saved_models"

os.makedirs(OUTPUT_DIR, exist_ok=True)
os.makedirs(MODEL_DIR, exist_ok=True)

In [ ]:
import torch
import torch.nn as nn

class LSTMModel(nn.Module):
    def __init__(self, hidden_dim=50, num_layers=4, dropout=0.2):
        super().__init__()

        self.lstm = nn.LSTM(
            input_size=1,
            hidden_size=hidden_dim,
            num_layers=num_layers,
            dropout=dropout,
            bidirectional=False,
            batch_first=True
        )

        self.fc = nn.Linear(hidden_dim, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        out, _ = self.lstm(x)
        out = out[:, -1, :]   # last timestep
        out = self.fc(out)
        return self.sigmoid(out)

In [ ]:
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model = LSTMModel(hidden_dim=50, num_layers=4, dropout=0.2).to(DEVICE)

criterion = nn.BCELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=1e-4)

EPOCHS = 8
best_val_acc = 0.0

In [ ]:
from tqdm.auto import tqdm
from sklearn.metrics import classification_report, confusion_matrix

In [ ]:
train_losses = []
train_accs = []
val_losses = []
val_accs = []

for epoch in range(EPOCHS):
    print(f"\nEpoch {epoch+1}/{EPOCHS}")

    model.train()
    train_loss = 0.0
    correct, total = 0, 0

    for x_batch, y_batch in tqdm(train_loader, desc="Training", leave=False):
        x_batch = x_batch.to(DEVICE)
        y_batch = y_batch.to(DEVICE).unsqueeze(1)

        optimizer.zero_grad()
        preds = model(x_batch)
        loss = criterion(preds, y_batch)
        loss.backward()
        optimizer.step()

        train_loss += loss.item()
        pred_labels = (preds > 0.5).int()
        correct += (pred_labels == y_batch).sum().item()
        total += y_batch.size(0)

    avg_train_loss = train_loss / len(train_loader)
    train_losses.append(avg_train_loss)
    train_acc = correct / total
    train_accs.append(train_acc)

    model.eval()
    val_loss = 0.0
    correct, total = 0, 0

    with torch.no_grad():
        for x_batch, y_batch in tqdm(val_loader, desc="Validation", leave=False):
            x_batch = x_batch.to(DEVICE)
            y_batch = y_batch.to(DEVICE).unsqueeze(1)

            preds = model(x_batch)
            loss = criterion(preds, y_batch)
            val_loss += loss.item()

            pred_labels = (preds > 0.5).int()
            correct += (pred_labels == y_batch).sum().item()
            total += y_batch.size(0)

    avg_val_loss = val_loss / len(val_loader)
    val_losses.append(avg_val_loss)
    val_acc = correct / total
    val_accs.append(val_acc)

    print(f"Train Loss: {avg_train_loss} | Train Acc: {train_acc} | "
          f"Val Loss: {avg_val_loss} | Val Acc: {val_acc}")

    if val_acc > best_val_acc:
        best_val_acc = val_acc
        torch.save(model.state_dict(), f"{MODEL_DIR}/lstm.pth")
        print("Saved best model")

In [ ]:
plt.figure(figsize=(14,5))

# Loss
plt.subplot(1, 2, 1)
plt.plot(range(1, EPOCHS+1), train_losses, label="Train Loss", marker="o")
plt.plot(range(1, EPOCHS+1), val_losses, label="Validation Loss", marker="o")
plt.title("LSTM Loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.xticks(range(1, EPOCHS+1))
plt.legend()
plt.grid(True)

# Accuracy
plt.subplot(1, 2, 2)
plt.plot(range(1, EPOCHS+1), train_accs, label="Train Acc", marker="o")
plt.plot(range(1, EPOCHS+1), val_accs, label="Validation Acc", marker="o")
plt.title("LSTM Accuracy")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.xticks(range(1, EPOCHS+1))
plt.legend()
plt.grid(True)

plt.tight_layout()
plt.savefig(f"{OUTPUT_DIR}/lstm_train_val_metrics.png", dpi=300)
plt.show()

In [ ]:
y_true, y_pred = [], []

model.eval()
with torch.no_grad():
    for x_batch, y_batch in tqdm(val_loader, desc="Evaluating", leave=False):
        x_batch = x_batch.to(DEVICE)

        preds = model(x_batch).squeeze()
        preds = (preds > 0.5).int().cpu().numpy()

        y_pred.extend(preds)
        y_true.extend(y_batch.numpy())

y_true = np.array(y_true)
y_pred = np.array(y_pred)

In [ ]:
# Reports
report = classification_report(y_true, y_pred)
with open(f"{OUTPUT_DIR}/lstm_classification_report.txt", "w") as f:
    f.write(report)

pd.DataFrame(
    classification_report(y_true, y_pred, output_dict=True)
).transpose().to_csv(f"{OUTPUT_DIR}/lstm_classification_report.csv")

# Predictions
np.save(f"{OUTPUT_DIR}/y_val_lstm.npy", y_true)
np.save(f"{OUTPUT_DIR}/y_lstm_pred.npy", y_pred)

# Conf matrix
cm = confusion_matrix(y_true, y_pred)

plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt="d", cmap="rocket",
            xticklabels=["Human","AI"],
            yticklabels=["Human","AI"])
plt.title("LSTM Confusion Matrix")
plt.tight_layout()
plt.savefig(f"{OUTPUT_DIR}/lstm_confusion_matrix.png", dpi=300)
plt.show()

### BI-LSTM

In [ ]:
class BiLSTM(nn.Module):
    def __init__(self, hidden_dim=50, num_layers=4, dropout=0.2):
        super().__init__()

        self.lstm = nn.LSTM(
            input_size=1,
            hidden_size=hidden_dim,
            num_layers=num_layers,
            dropout=dropout,
            bidirectional=True,
            batch_first=True
        )

        self.fc = nn.Linear(hidden_dim * 2, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        out, _ = self.lstm(x)
        out = out[:, -1, :]
        out = self.fc(out)
        return self.sigmoid(out)

In [ ]:
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = BiLSTM().to(DEVICE)
criterion = nn.BCELoss()
optimizer = Adam(model.parameters(), lr=1e-4)
EPOCHS = 8
best_val_acc = 0.0

In [ ]:
train_losses = []
train_accs = []
val_losses = []
val_accs = []

for epoch in range(EPOCHS):
    print(f"\nEpoch {epoch+1}/{EPOCHS}")

    model.train()
    train_loss = 0.0
    correct, total = 0, 0

    for x_batch, y_batch in tqdm(train_loader, desc="Training", leave=False):
        x_batch = x_batch.to(DEVICE)
        y_batch = y_batch.to(DEVICE).unsqueeze(1)

        optimizer.zero_grad()
        preds = model(x_batch)
        loss = criterion(preds, y_batch)
        loss.backward()
        optimizer.step()

        train_loss += loss.item()
        pred_labels = (preds > 0.5).int()
        correct += (pred_labels == y_batch).sum().item()
        total += y_batch.size(0)

    avg_train_loss = train_loss / len(train_loader)
    train_losses.append(avg_train_loss)
    train_acc = correct / total
    train_accs.append(train_acc)

    model.eval()
    val_loss = 0.0
    correct, total = 0, 0

    with torch.no_grad():
        for x_batch, y_batch in tqdm(val_loader, desc="Validation", leave=False):
            x_batch = x_batch.to(DEVICE)
            y_batch = y_batch.to(DEVICE).unsqueeze(1)

            preds = model(x_batch)
            loss = criterion(preds, y_batch)
            val_loss += loss.item()

            pred_labels = (preds > 0.5).int()
            correct += (pred_labels == y_batch).sum().item()
            total += y_batch.size(0)

    avg_val_loss = val_loss / len(val_loader)
    val_losses.append(avg_val_loss)
    val_acc = correct / total
    val_accs.append(val_acc)

    print(f"Train Loss: {avg_train_loss} | Train Acc: {train_acc} | "
          f"Val Loss: {avg_val_loss} | Val Acc: {val_acc}")

    if val_acc > best_val_acc:
        best_val_acc = val_acc
        torch.save(model.state_dict(), f"{MODEL_DIR}/bi_lstm.pth")
        print("Saved best model")

In [ ]:
plt.figure(figsize=(14,5))

# Loss
plt.subplot(1, 2, 1)
plt.plot(range(1, EPOCHS+1), train_losses, label="Train Loss", marker="o")
plt.plot(range(1, EPOCHS+1), val_losses, label="Validation Loss", marker="o")
plt.title("BI-LSTM Loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.xticks(range(1, EPOCHS+1))
plt.legend()
plt.grid(True)

# Accuracy
plt.subplot(1, 2, 2)
plt.plot(range(1, EPOCHS+1), train_accs, label="Train Acc", marker="o")
plt.plot(range(1, EPOCHS+1), val_accs, label="Validation Acc", marker="o")
plt.title("BI-LSTM Accuracy")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.xticks(range(1, EPOCHS+1))
plt.legend()
plt.grid(True)

plt.tight_layout()
plt.savefig(f"{OUTPUT_DIR}/bi_lstm_train_val_metrics.png", dpi=300)
plt.show()

In [ ]:
y_true, y_pred = [], []

model.eval()
with torch.no_grad():
    for x_batch, y_batch in tqdm(val_loader, desc="Evaluating", leave=False):
        x_batch = x_batch.to(DEVICE)

        preds = model(x_batch).squeeze()
        preds = (preds > 0.5).int().cpu().numpy()

        y_pred.extend(preds)
        y_true.extend(y_batch.numpy())

y_true = np.array(y_true)
y_pred = np.array(y_pred)

In [ ]:
# Reports
report = classification_report(y_true, y_pred)
with open(f"{OUTPUT_DIR}/bi_lstm_classification_report.txt", "w") as f:
    f.write(report)

pd.DataFrame(
    classification_report(y_true, y_pred, output_dict=True)
).transpose().to_csv(f"{OUTPUT_DIR}/bi_lstm_classification_report.csv")

# Predictions
np.save(f"{OUTPUT_DIR}/y_val_bi_lstm.npy", y_true)
np.save(f"{OUTPUT_DIR}/y_bi_lstm_pred.npy", y_pred)

# Conf matrix
cm = confusion_matrix(y_true, y_pred)

plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt="d", cmap="rocket",
            xticklabels=["Human","AI"],
            yticklabels=["Human","AI"])
plt.title("BI-LSTM Confusion Matrix")
plt.tight_layout()
plt.savefig(f"{OUTPUT_DIR}/bi_lstm_confusion_matrix.png", dpi=300)
plt.show()